try to fix doc test
- `range(...)` was replaced by range syntax
- `Thread::spawn(...)` spawns a detached thread now (and has no `detach()` method anymore).

It still panics on my machine (with `thread '_1' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:144`) and throws an error about std being unstable, but the two changes should be alright...